version: '3'
services:
  app:
    build:  
      context: .
      dockerfile: Dockerfile 

    container_name: django
    restart: always
    ports:
      - "8000:8000"    
    volumes:
      - .:/srv/plugin
      - ./log:/var/log
    command: 
      gunicorn --workers=3 --bind 0.0.0.0:8000 API.wsgi:application
      
    expose: 
      - "8000"

  nginx:
    container_name: nginx
    hostname: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile 
    restart: always
    volumes:
      - .:/srv/plugin
    ports:
      - "80:80"
    depends_on:
      - app


  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - "5672:5672"

  worker:
    container_name: celery
    hostname: celery
    build: .
    volumes:
      - .:/srv/plugin
    environment:
      - C_FORCE_ROOT=true
    command: 
      celery -A API worker -l info
    links:
      - rabbit
      - celery-beat
    depends_on:
      - rabbit
  
  celery-beat:
    container_name: celery-beat
    hostname: beat
    environment:
      - C_FORCE_ROOT=true
    build: .
    command: celery -A API beat -l debug --pidfile=./celerybeat.pid
    volumes:
      - .:/srv/plugin
    links:
      - rabbit
    depends_on:
      - rabbit